city_council/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('council.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "City Council Admin"
admin.site.site_title = "City Council Admin Portal"
admin.site.index_title = "Welcome to City Council Admin Portal"

council/urls.py
from django.urls import path

from . import views

app_name = 'council'

urlpatterns = [
    path('', views.index, name='index'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("profile", views.profile, name="profile"),
    path('edit-profile/<uuid:employee_id>/', views.edit_profile, name="edit-profile"),
    path('delete-performance-review/<int:id>/delete', views.delete_view, 'delete_view'),
    path('edit-performance-review/<uuid:review_id>/', views.edit_performance_review, name="edit_performance_review"),
    path('create-performance-review/', views.create_performance_review, name="create_performance_review"),
]

council/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

MARITAL_STATUS_CHOICES = (
    ('single', 'Single'),
    ('married', 'Married'),
    ('divorced', 'Divorced'),
)


class User(AbstractUser):

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)
    
    class Meta:
        verbose_name = "Employee"
        verbose_name_plural = "Employees"

class Department(models.Model):  
    
      
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name = 'Department Name')
    department_number = models.CharField(max_length=100, unique=True, blank=True, null=True)
    sub_departments = models.TextField(max_length=500, blank=True, null=True, verbose_name = 'Sub Departments')
    date_created = models.DateField(auto_now_add=True, null=True)

    class Meta:
        ordering = ("-date_created",)
        verbose_name = "Departments"
        verbose_name_plural = "Departments"

    def __str__(self):
        return self.name


class Employee(models.Model):
    

    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name = 'Employee', related_name="employee")
    works_number = models.CharField(max_length=15, verbose_name = 'Works Number')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="dep")
    sex = models.CharField(choices=GENDER_CHOICES, max_length=255)
    marital_status = models.CharField(choices=MARITAL_STATUS_CHOICES, max_length=255, verbose_name = 'Marital Status')
    salary = models.DecimalField(max_digits=12, decimal_places=2)
    photo = models.ImageField(max_length=255, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True, verbose_name = 'Date of Birth', help_text='Use date format YYYY-MM-DD')
    home_address = models.TextField(max_length=100, blank=True, null=True, verbose_name = 'Home Address')
    phone_number = models.CharField(max_length=15, blank=True, null=True, verbose_name = 'Phone Number')
    next_of_kin_name = models.CharField( blank=True, null=True,max_length=100, verbose_name = 'Next of Kin Name')
    next_of_kin_phone_number = models.CharField(blank=True, null=True, max_length=15, verbose_name = 'Next of Kin Contact Number')
    grade = models.CharField(blank=True, null=True,max_length=255)
    qualifications = models.TextField(max_length=500, blank=True, null=True)
    medical_records = models.TextField(max_length=500, blank=True, null=True, verbose_name = 'Medical Records')
    leave_record = models.TextField(max_length=500, blank=True, null=True, verbose_name = 'Leave Record')
    displinary_record = models.TextField(max_length=500, blank=True, null=True, verbose_name = 'Displinary Record')
    date_joined = models.DateField(auto_now_add=True, null=True)

    class Meta:
        ordering = ("-date_joined",)
        verbose_name = "Employee Profile"
        verbose_name_plural = "Employee Profiles"

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class DepartmentManager(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name="worker")
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="field")
    from_date = models.DateField(auto_now_add=True, null=True)
    to_date = models.DateField(blank=True, null=True)

    class Meta:
        ordering = ("-from_date",)
        verbose_name = "Department Manager"
        verbose_name_plural = "Department Managers"

    def __str__(self):
        return "{} - {}".format(self.employee, self.department)

class WeeklyPerfomanceReview(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
        
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name="staff_member")
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="dept")

    week_starting = models.DateField(null=True, help_text='Use date format YYYY-MM-DD')
    week_ending = models.DateField(null=True, help_text='Use date format YYYY-MM-DD')

    ## Work Plan 
    activity1 = models.CharField(max_length=500, verbose_name = 'Activity 1')
    work_to_be_done1 = models.CharField(max_length=500, verbose_name = 'Work To Be Done (1)')
    activity2 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Activity 2')
    work_to_be_done2 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work To Be Done (2)')
    activity3 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Activity 3')
    work_to_be_done3 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work To Be Done (3)')
    activity4 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Activity 4')
    work_to_be_done4 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work To Be Done (4)')
    activity5 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Activity 5')
    work_to_be_done5 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work To Be Done (5)')
    activity6 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Activity 6')
    work_to_be_done6 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work To Be Done (6)')
    activity7 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Activity 7')
    work_to_be_done7 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work To Be Done (7)')


    ## Results
    work_done1 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work Done (Day 1)')
    evidence_of_work_done1 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Evidence of Work Done (Day 1)')
    work_done2 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work Done (Day 2)')
    evidence_of_work_done2 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Evidence of Work Done (Day 2)')
    work_done3 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work Done (Day 3)')
    evidence_of_work_done3 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Evidence of Work Done (Day 3)')
    work_done4 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work Done (Day 4)')
    evidence_of_work_done4 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Evidence of Work Done (Day 4)')
    work_done5 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Work Done (Day 5)')
    evidence_of_work_done5 = models.CharField(max_length=500, blank=True, null=True, verbose_name = 'Evidence of Work Done (Day 5)')
    
    
    evaluation = models.TextField(max_length=500, blank=True, null=True, verbose_name = 'Evaluation of Work Done (RESULTS):')
    innovations = models.TextField(max_length=500, blank=True, null=True, verbose_name = 'Innovation and Initiatives for the Week')
    
    # Checking Process

    comment_by_supervisor = models.TextField(max_length=100, blank=True, null=True, verbose_name = 'Comments by immediate Supervisor')
    checked_and_approved = models.BooleanField(default=False, verbose_name = 'Checked and Approved as a true record')
    comment_by_director = models.TextField(max_length=100, blank=True, null=True, verbose_name = 'Comments by Department Director')
    comment_by_assistant_director = models.TextField(max_length=100, blank=True, null=True, verbose_name = 'Comments by Assistant Director')
   
   
    created_on = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ("-created_on",)
        verbose_name = "Weekly Perfomance Review"
        verbose_name_plural = "Weekly Perfomance Reviews"
    def __str__(self):
        return '{} {} for the for week ending {}'.format(self.employee.user.first_name, self.employee.user.last_name, self.week_ending)

council/forms.py
from django import forms
from django.forms import ModelForm, Textarea, RadioSelect
from .models import WeeklyPerfomanceReview, Employee
from django.utils.translation import ugettext_lazy as _


# class DateInput(forms.DateTimeInput):
#     input_type = 'date'

class WeeklyPerfomanceReviewForm(ModelForm):

    def __init__(self, *args, **kwargs):
       super(WeeklyPerfomanceReviewForm, self).__init__(*args, **kwargs)
       self.fields['comment_by_supervisor'].widget.attrs['readonly'] = True
       self.fields['comment_by_assistant_director'].widget.attrs['readonly'] = True
       self.fields['checked_and_approved'].disabled = True
       self.fields['comment_by_director'].widget.attrs['readonly'] = True

       
    class Meta:
        model = WeeklyPerfomanceReview
        exclude = ('employee', 'department')
        labels = {
            "week_starting": _(""),
            "week_ending": _(""),
            "activity1": _("Activity"),
            "activity2": _("Activity"),
            "activity3": _("Activity"),
            "activity4": _("Activity"),
            "activity5": _("Activity"),
            "activity6": _("Activity"),
            "activity7": _("Activity"),
            "work_to_be_done1": _("Work to be Done"),
            "work_to_be_done2": _("Work to be Done"),
            "work_to_be_done3": _("Work to be Done"),
            "work_to_be_done4": _("Work to be Done"),
            "work_to_be_done5": _("Work to be Done"),
            "work_to_be_done6": _("Work to be Done"),
            "work_to_be_done7": _("Work to be Done"),
            "work_done1": _("Work Done (Day 1)"),
            "work_done2": _("Work Done (Day 2)"),
            "work_done3": _("Work Done (Day 3)"),
            "work_done4": _("Work Done (Day 4)"),
            "work_done5": _("Work Done (Day 5)"),
            "evidence_of_work_done1": _("Evidence of Work Done"),
            "evidence_of_work_done2": _("Evidence of Work Done"),
            "evidence_of_work_done3": _("Evidence of Work Done"),
            "evidence_of_work_done4": _("Evidence of Work Done"),
            "evidence_of_work_done5": _("Evidence of Work Done"),
            "evaluation": _("Evaluation of Work Done (RESULTS):"),
            "innovations": _("Innovation and Initiatives for the Week"),
            "comment_by_supervisor": _("Comments by Immediate Supervisor"),
            "comment_by_assistant_director": _("Comments by Assistant Director of Finance"),
            "comment_by_director": _("Comments by Director of Finance"),
            "checked_and_approved": _("Checked and Approved as a true record"),
        }
        widgets = {
            'evaluation': Textarea(attrs={'cols': 20, 'rows': 5}),
            'innovations': Textarea(attrs={'cols': 20, 'rows': 5}),
            'comment_by_supervisor': Textarea(attrs={'cols': 20, 'rows': 5}),
            'comment_by_assistant_director': Textarea(attrs={'cols': 20, 'rows': 5}),
            'comment_by_director': Textarea(attrs={'cols': 20, 'rows': 5}),
            # 'week_starting': DateInput(),
            # 'week_ending': DateInput(),
        }


class EmployeeProfileForm(ModelForm):
      
    class Meta:
        model = Employee
        exclude = ('id', 'user', 'department', 'medical_records', 'leave_record', 'displinary_record', 'date_joined', 'salary', 'grade', 'qualifications' , 'sex', 'works_number' )
        labels = {
            "photo": _(""),
            "date_of_birth": _(""),
            "marital_status": _(""),
            "home_address": _(""),
            "phone_number": _(""),
            "next_of_kin_name": _(""),
            "next_of_kin_phone_number": _(""),
        }
        widgets = {
            'home_address': Textarea(attrs={'cols': 20, 'rows': 5}),
            # 'date_of_birth': DateInput(),
        }

council/views.py
from council.models import Employee, Department
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import WeeklyPerfomanceReviewForm, EmployeeProfileForm
from django.shortcuts import get_object_or_404
from .models import WeeklyPerfomanceReview
from django.shortcuts import redirect
from django.contrib import messages


def index(request):
    if not request.user.is_authenticated:
        return render(request, "council/login.html", {"message": None})

    employee =  get_object_or_404(Employee, user=request.user)
    table_info = WeeklyPerfomanceReview.objects.filter(employee=employee)[0:10]
    data = {
        "user": request.user,
        "table_info" : table_info
      }
    return render(request, 'council/dashboard.html', data)


def login_view(request):
      username = request.POST["username"]
      password = request.POST["password"]
      user = authenticate(request, username=username, password=password)
      if user is not None:
          login(request, user)
          if user.is_staff:
            return HttpResponseRedirect(reverse("admin:index"))
          else:
            return HttpResponseRedirect(reverse("council:index"))
      else:
          return render(request, "council/login.html", {"message": "Invalid credentials."})


def logout_view(request):
    logout(request)
    return render(request, "council/login.html", {"message": "Logged out."})


def profile(request):
    employee =  get_object_or_404(Employee, user=request.user)
    data = {
        "user": request.user,
        "employee": employee
      }
    return render(request, 'council/profile.html', data)


# delete view for details
def delete_view(request, id):
    context ={}
    obj = get_object_or_404(WeeklyPerfomanceReview, id = id)
    if request.method =="POST":
        # delete object
        obj.delete()
        # after deleting redirect to 
        # home page
        return HttpResponseRedirect("/")
  
    return render(request, "delete_view.html", context)


def create_performance_review(request):
    form = WeeklyPerfomanceReviewForm()

    if request.method == "POST":
        form = WeeklyPerfomanceReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            employee =  get_object_or_404(Employee, user=request.user)
            department =  get_object_or_404(Department, id=employee.department.id)
            review.employee = employee
            review.department = department
            review.save()
            messages.success(request, 'Your perfomance review has been created.')
            return HttpResponseRedirect(reverse("council:index"))

    return render(request, "council/create_performance_review.html", {
        "form" : form
    })


def edit_performance_review(request, review_id):
    form = WeeklyPerfomanceReviewForm(instance = WeeklyPerfomanceReview.objects.get(id=review_id))

    if request.method == "POST":
        form = WeeklyPerfomanceReviewForm(request.POST, instance = WeeklyPerfomanceReview.objects.get(id=review_id))

        if form.is_valid():
            form.save()
            messages.info(request, 'Your perfomance review has been updated.')
            return HttpResponseRedirect(reverse("council:index"))

    return render(request, "council/edit_performance_review.html", {
        "form" : form
    })

def edit_profile(request, employee_id):
    form = EmployeeProfileForm(instance = Employee.objects.get(id=employee_id))
    employee =  get_object_or_404(Employee, user=request.user)

    if request.method == "POST":
        form = EmployeeProfileForm(request.POST, request.FILES, instance = Employee.objects.get(id=employee_id))
        print("gets here")

        if form.is_valid():
            print("works")
            form.save()
            messages.info(request, 'Your profile has been updated.')
            return HttpResponseRedirect(reverse("council:profile"))

    return render(request, "council/edit_profile.html", {
        "form" : form,
        'employee' : employee
    })

council/templates/council/dashboard.html
{% extends 'council/index.html' %}
{% load static %}

{% block title %}

<title> Dashboard | City Council</title>

{% endblock title %}



{% block content %}
<section id="main-content">
    <section class="wrapper">
      <!--overview start-->
      <div class="row">
        <div class="col-lg-12">
          <h3 class="page-header"><i class="fa fa-laptop"></i> Dashboard</h3>
          <ol class="breadcrumb">
            <li><i class="fa fa-home"></i><a href="{% url 'council:index' %}">Home</a></li>
            <li><i class="fa fa-laptop"></i>Dashboard</li>
          </ol>
        </div>
      </div>


      <!-- page start-->
      <div class="row">
        <div class="col-lg-12">

          {% if messages %}
            {% for msg in messages %}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{msg.message}}
              </div>
            {% endif %}
            {% endfor %}
          {% endif %}

          
          

          {% if messages %}
          {% for msg in messages %}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.INFO %}
              <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{msg.message}}
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}


          <section class="panel">
            <header class="panel-heading">
              Perfomance Reviews Table
            </header>



            {% if not table_info %}
            <p class="text-center">You currently have no perfomance reviews yet! <a href="{% url 'council:create_performance_review' %}" class="text-primary">Create One</a> </p>

            {% else %}
            <table class="table table-striped table-advance table-hover">
              <tbody>
                <tr>
                  <th><i class="icon_profile"></i> Full Name</th>
                  <th><i class="icon_documents_alt"></i> Activities</th>
                  <th><i class="icon_calendar"></i> Date</th>
                  <th><i class="icon_check_alt"></i> Approved</th>
                  <th><i class="icon_cogs"></i> Action</th>
                </tr>
                {% for item in table_info %}
                <tr>
                  <td>{{item.employee}}</td>
                  {% if item.work_done1 and item.work_to_be_done1 %}
                  <td>{{item.work_done1|truncatechars:35 }} {{item.evidence_of_work_done1|truncatechars:35 }}</td>
                  {% else %}
                  <td>{{item.activity1|truncatechars:35 }} {{item.work_to_be_done1|truncatechars:35 }}</td>
                  {% endif %}
                  <td>{{item.created_on}}</td>
                    {% if item.checked_and_approved %}
                    <td>Checked and Approved</td>
                    {% else %}
                    <td>Pending</td>
                    {% endif %}
                  <td>
                    <div class="btn-group">
                      <a class="btn btn-primary" href="{% url 'council:edit_performance_review' item.id %}"><i class="icon_pencil"></i></a>
                      <a class="btn btn-success" href="{% url 'council:create_performance_review' %}"><i class="icon_plus_alt2"></i></a>
                      <!-- <a class="btn btn-danger" href="#"><i class="icon_close_alt2"></i></a> -->
                    </div>
                  </td>
                </tr>

              {% endfor %}
              </tbody>
            </table>

            {% endif %}

          </section>
        </div>
      </div>
      <!-- page end-->
      
    </section>
  
  </section>
  {% endblock content %}

council/templates/council/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="City Council - Employee Management System">
  <meta name="author" content="Ashley T Shumba">
  <meta name="keyword" content="City Council , Employee Management System">
  <link rel="shortcut icon" href="{% static 'council/img/favicon.jpg' %}">

  <title>Login | City Council</title>

  <!-- Bootstrap CSS -->
  <link href="{% static 'council/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- bootstrap theme -->
  <link href="{% static 'council/css/bootstrap-theme.css' %}" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="{% static 'council/css/elegant-icons-style.css' %}" rel="stylesheet" />
  <link href="{% static 'council/css/font-awesome.css' %}" rel="stylesheet" />
  <!-- Custom styles -->
  <link href="{% static 'council/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'council/css/style-responsive.css' %}" rel="stylesheet" />

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <!-- =======================================================
      Theme Name: NiceAdmin
      Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>

<body class="login-img3-body">

  <div class="container">

      <form class="login-form"action="{% url 'council:login' %}" method="post">
        {% csrf_token %}

        <div class="login-wrap">
        <p class="login-img"><i class="icon_lock_alt"></i></p>

        {% if message %}
    <div class="m-2">
      <p class="text-center font-weight-bold text-danger">{{ message }}</p> 
    </div>
{% endif %}
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_profile"></i></span>
          <input type="text" name="username" class="form-control" placeholder="Username" autofocus>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_key_alt"></i></span>
          <input type="password" name="password" class="form-control" placeholder="Password">
        </div>
        <label class="checkbox">
                <!-- <input type="checkbox" value="remember-me"> Remember me -->
                <!-- <span class="pull-right"> <a href="{% url 'admin:index' %}"> Login as Admin</a></span> -->
            </label>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
        <!-- <button class="btn btn-info btn-lg btn-block" type="submit">Signup</button> -->
      </div>
    </form>
    <div class="text-right">
      <div class="credits">
          <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version form: https://bootstrapmade.com/buy/?theme=NiceAdmin
          -->
          <!-- Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
        </div>
    </div>
  </div>


</body>

</html>

council/templates/council/performance.html
{% extends 'council/index.html' %}
{% load static %}


{% block title %}

<title> Activities | City Council</title>

{% endblock title %}


{% block content %}
<section id="main-content">
  <section class="wrapper">


          <!--overview start-->
          <div class="row">
            <div class="col-lg-12">
              <h3 class="page-header"><i class="fa fa-laptop"></i> Performance</h3>
              <ol class="breadcrumb">
                <li><i class="fa fa-home"></i><a href="{% url 'council:index' %}">Home</a></li>
                <li><i class="fa fa-laptop"></i>Performance</li>
              </ol>
            </div>
          </div>

    <!-- Basic Forms & Horizontal Forms-->
<!-- 
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">
            Work Plan
          </header>
          <div class="panel-body">
            <form role="form" action="{% url 'council:index' %}" method="POST">
              <div class="row">
                <div class="col-lg-6">

              <div class="form-group">
                <label class="control-label col-sm-4">Week Starting</label>
                <div class="col-sm-6">
                  <input id="dp1" type="text" name="weekstarting" placeholder="{% now 'SHORT_DATE_FORMAT' %}" size="16" class="form-control">
                </div>
              </div>
</div>
              <div class="col-lg-6">

              <div class="form-group">
                <label class="control-label col-sm-4">Week Ending</label>
                <div class="col-sm-6">
                  <input id="dp1" type="text" name="weekending" placeholder="{% now 'SHORT_DATE_FORMAT' %}" size="16" class="form-control">
                </div>
              </div>
</div>
</div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="activity1">Activity </label>
                    <input type="text" name="activity1" class="form-control" id="activity1" >
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="worktobedone1">Work to be done </label>
                    <input type="text" name="worktobedone1"  class="form-control" id="worktobedone1" >
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="activity2">Activity </label>
                    <input type="text" name="activity2" class="form-control" id="activity2" >
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="worktobedone2">Work to be done </label>
                    <input type="text" name="worktobedone2" class="form-control" id="worktobedone2" >
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="activity3">Activity </label>
                    <input type="text" name="activity3" class="form-control" id="activity3" >
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="worktobedone3">Work to be done </label>
                    <input type="text" name="worktobedone3" class="form-control" id="worktobedone3" >
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="activity4">Activity </label>
                    <input type="text" name="activity4" class="form-control" id="activity4" >
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="worktobedone4">Work to be done </label>
                    <input type="text" name="worktobedone4" class="form-control" id="worktobedone4" >
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="activity5">Activity </label>
                    <input type="text" name="activity5" class="form-control" id="activity5" >
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="worktobedone5">Work to be done </label>
                    <input type="text" name="worktobedone5" class="form-control" id="worktobedone5" >
                  </div>
                </div>
              </div>
              
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>

          </div>
        </section>
      </div>
    </div>
  -->
    <!-- page end-->
  </section>
</section>
  {% endblock content %}